ENABLE_PLUGIN: true
DUNGEON_GENERATE_WORLD: 'dungeon'
DUNGEON_GENERATE_COMMAND: true
DUNGEON_GENERATE_TRIGGER_RADIUS: 60
DUNGEON_GENERATE_UNDERGROUND_HIGTH: 62
Generate:
  ENABLE_DUNGEON_MOSSY: true
  ENABLE_DUNGEON_JUNGLECAVE: true
  ENABLE_DUNGEON_RUINS: true
  ENABLE_DUNGEON_TOWERS: true
message:
  help:
    0:
      - '&athis Plugin helps.'
      - '&a******************************'
      - '&a*     ResorceDungeons'
      - '&a*     %version%'
      - '&a*     Auther : %auther%'
      - '&a******************************'
      - '/RDhelp 1'
    1:
      - '&a/BDGenerate [Dungeon]'
      - '&aGenerating Dungeon. Allow Generate World %dungeon_world% .'
      - '&aCan not is Undo!'
      - '&anext /RDHelp 2'
    2:
      - '&a/RDReload [option]'
      - '&aThis Plugin Reload.'
      - '&a[option] : disable is plugin stoping. Only console.'
      - '&anext /RDHelp 3'
    error_args: '&aNo argment.'
  reload:
    no_args: '&aNo argment.'
    reload: '&aPlugin has reloaded!'
    disable_console: '&aConsole Only argment!'
  generator:
    console: '&Console dney command!'
    no_args: '&aPlease Dungeon name! /RDGnerate [dungeon_name]'
    error_args: '&aNo argment.'
    error_not_exist_dungeon: '&aNot exist Dungeon name!'
    error_not_dungeonworld: '&aDo not Dungeon Generate World!'
    test_onlinemode_off: '&aPlease server config is online-mode true!'
    test_other_player: '&aYou can not generate dungeon!'
  sign:
    not_chenge: '&aDo not describe the [RDungeons]!'